name: java ci/cd pipeline to tomcat

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: [self-hosted,linux]

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: ensure maven is installed
        run: |
          if ! command -v mvn &> /dev/null;then
            echo "Maven not found.Installing..."
            sudo dnf install -y maven
          else
            echo "maven is already installed"
          fi
          mvn -version

      - name: cache maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
          restore-keys: |
            ${{runner.os}}-maven-

      - name: build with maven
        run: mvn clean package -DskipTests

      - name: upload war artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp
          path: target/*.war

      - name: install sonar qube scanner cli
        run: |
          if [ ! -d "$HOME/sonar-scanner-cli" ]; then

            echo "downloading sonarqube scanner cli..."
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.3.0.5189-linux-x64.zip -O /tmp/sonar-scanner.zip
            unzip /tmp/sonar-scanner.zip -d $HOME
            mv $HOME/sonar-scanner-7.3.0.5189-linux-x64 $HOME/sonar-scanner-cli
          fi
          export PATH=$HOME/sonar-scanner-cli/bin:$PATH
          sonar-scanner -v

      - name: SonarQube Analysis
        env:
          SONAR_HOST: ${{ secrets.SONAR_HOST }}
          SONAR_LOGIN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "SonarQube server URL: $SONAR_HOST"
          curl -I $SONAR_HOST
          mvn sonar:sonar \
            -Dsonar.projectKey=hotstar \
            -Dsonar.host.url=$SONAR_HOST \
            -Dsonar.login=$SONAR_LOGIN







  deploy: 
   runs-on: [self-hosted,linux]
   needs: build
   environment: production

   steps:
     - name: download war artifact
       uses: actions/download-artifact@v4
       with:
         name: myapp

     - name: deploy to tomcat
       run: |
         WAR_FILE=$(ls *.war)
         echo "Deploying $WAR_FILE to tomcat..."
         curl -v --upload-file "$WAR_FILE"\
           "http://${{secrets.TOMCAT_USER}}:${{secrets.TOMCAT_PASSWORD}}@${{secrets.TOMCAT_HOST}}/manager/text/deploy?path=/myapp&update=true"

      
     - name: verify deployment
       run: |
        curl -l http://${{secrets.TOMCAT_HOST}}/myapp
